"""LangGraph utils package: node helpers, partial data extraction, and graph routing."""

from .llm_call_io import save_llm_call_input, save_llm_call_output
from .node_helpers import (
    LLM_COL_VALIDATE_TAG,
    REVENUE_PRIORITY_KEYWORDS,
    assign_chart_category,
    assign_result_category,
    build_aggregation_details,
    filter_charts_with_all_zeros,
    build_analytical_schema_context,
    build_measure_to_category,
    build_metric_to_measures_from_analysis_plan,
    build_column_types_for_preplan,
    check_timeline_availability,
    clean_sql_plan,
    extract_and_parse_json,
    extract_chart_data_for_llm,
    extract_date_filters_from_state,
    find_date_field_in_table,
    find_date_field_from_tables,
    get_column_type,
    log_llm_invalid_columns,
    normalize_sql_plan_to_tables_format,
    parse_json_response,
    parse_json_response_required_dict,
    resolve_dataset_key,
    save_prompt_to_json,
    select_revenue_priority_metrics,
    try_repair_truncated_analytical_selection,
    try_repair_truncated_json,
    validate_llm_columns,
)
from .node_helpers import _extract_queries_from_response  # used by generate_sql node

from .partial_data import (
    extract_all_partial_data_fields,
    extract_full_source_data,
    extract_source_data_metadata,
    extract_source_data_preview,
)

from .graph_routing import (
    analytical_fetch_plan_sink_node,
    computation_engine_ready_node,
    computation_engine_ready_sink_node,
    db_execution_ready_node,
    db_execution_ready_sink_node,
    is_sap_datasphere,
    moderate_post_fetch_node,
    route_after_prepare_analytical_schema,
    route_after_analytical_column_selection,
    route_after_analytical_fetch_plan,
    route_after_db_execution_ready,
    route_after_get_schema,
    route_after_get_schema_moderate,
    route_after_orchestration,
    route_after_query_analysis,
    route_after_sap_data_fetch,
    route_after_simple_column_selection,
    route_after_sql_plan,
    route_computation_engine_ready,
    sap_analytical_passthrough_node,
    sap_data_fetch_trigger_node,
)

from .step_details import extract_step_details

from .token_utils import (
    count_tokens,
    get_prompt_token_count,
    validate_prompt_tokens,
    truncate_metrics_by_priority_for_prompt,
    truncate_charts_for_prompt,
    sort_metrics_by_priority,
    DEFAULT_MAX_INPUT_PROMPT_TOKENS,
)

from .sap_fetch_helpers import (
    build_date_filter_expression,
    clean_odata_select,
    date_like_column_name,
    extract_date_columns_by_view,
    extract_date_columns_from_schema,
    filter_columns_for_api_call,
    get_allowed_columns_for_view,
    normalize_odata_rows_for_polars,
    pick_date_column_and_default_range,
)

__all__ = [
    "save_llm_call_input",
    "save_llm_call_output",
    "LLM_COL_VALIDATE_TAG",
    "REVENUE_PRIORITY_KEYWORDS",
    "analytical_fetch_plan_sink_node",
    "computation_engine_ready_node",
    "computation_engine_ready_sink_node",
    "db_execution_ready_node",
    "db_execution_ready_sink_node",
    "assign_chart_category",
    "assign_result_category",
    "build_aggregation_details",
    "filter_charts_with_all_zeros",
    "build_analytical_schema_context",
    "build_measure_to_category",
    "build_metric_to_measures_from_analysis_plan",
    "build_column_types_for_preplan",
    "check_timeline_availability",
    "find_date_field_in_table",
    "find_date_field_from_tables",
    "get_column_type",
    "clean_sql_plan",
    "extract_all_partial_data_fields",
    "extract_and_parse_json",
    "extract_chart_data_for_llm",
    "extract_date_filters_from_state",
    "extract_step_details",
    "count_tokens",
    "get_prompt_token_count",
    "validate_prompt_tokens",
    "truncate_metrics_by_priority_for_prompt",
    "truncate_charts_for_prompt",
    "sort_metrics_by_priority",
    "DEFAULT_MAX_INPUT_PROMPT_TOKENS",
    "extract_full_source_data",
    "extract_source_data_metadata",
    "extract_source_data_preview",
    "is_sap_datasphere",
    "log_llm_invalid_columns",
    "normalize_sql_plan_to_tables_format",
    "parse_json_response",
    "parse_json_response_required_dict",
    "resolve_dataset_key",
    "save_prompt_to_json",
    "moderate_post_fetch_node",
    "route_after_prepare_analytical_schema",
    "route_after_analytical_column_selection",
    "route_after_analytical_fetch_plan",
    "route_after_db_execution_ready",
    "route_after_get_schema",
    "route_after_get_schema_moderate",
    "route_after_orchestration",
    "route_after_query_analysis",
    "route_after_sap_data_fetch",
    "route_after_simple_column_selection",
    "route_after_sql_plan",
    "route_computation_engine_ready",
    "sap_analytical_passthrough_node",
    "sap_data_fetch_trigger_node",
    "select_revenue_priority_metrics",
    "try_repair_truncated_analytical_selection",
    "try_repair_truncated_json",
    "validate_llm_columns",
    # SAP fetch helpers
    "build_date_filter_expression",
    "clean_odata_select",
    "date_like_column_name",
    "extract_date_columns_by_view",
    "extract_date_columns_from_schema",
    "filter_columns_for_api_call",
    "get_allowed_columns_for_view",
    "normalize_odata_rows_for_polars",
    "pick_date_column_and_default_range",
]
